### ISSUE TITLE
もっとロゴをかわいくしたい

### ISSUE THREAD

**Issue by inaba-jun** [inaba-jun/personal-test#9]
もっとロゴをかわいくしたいです。今のロゴはちょっと怖いと思うのですが、このようなロゴはどうでしょうか。
<img width="227" alt="2018-06-04 17 21 12" src="https://user-images.githubusercontent.com/29134427/40906453-c52ae9e0-681b-11e8-8356-a032029856d1.png">

**Comment by inabajunmr** [comment]
![selfie-0](https://i.imgur.com/BXW4ned.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
最高すぎる

**Comment by inabajunmr** [comment]
![selfie-0](https://i.imgur.com/k5GYCJo.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
最高すぎる

**Comment by inabajunmr** [comment]
![selfie-0](https://i.imgur.com/HVpNYqQ.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
最高すぎる

**Comment by inabajunmr** [comment]
![selfie-0](https://i.imgur.com/g1itIgW.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
最高すぎる

**Comment by inaba-jun** [comment]
![selfie-0](https://i.imgur.com/XpanDob.jpg)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
最高です

**Comment by inaba-jun** [comment]
![selfie-0](https://i.imgur.com/Kux4Iz3.gif)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
最高ですね
